#!/usr/bin/env python3
"""
gen_scaler_header.py  –  Generate Inc/fall_scaler_data.h from scaler.npz

Usage:
    python3 tools/gen_scaler_header.py [--scaler scaler.npz] [--out Inc/fall_scaler_data.h]

The scaler.npz must contain:
    mean  –  shape (1, 30, 51), dtype float32
    std   –  shape (1, 30, 51), dtype float32
"""

import argparse
import os
import sys
from datetime import datetime

try:
    import numpy as np
except ImportError:
    sys.exit("numpy is required: pip install numpy")


TEMPLATE_HEADER = """\
/* Auto-generated by tools/gen_scaler_header.py from {npz_name} */
/* Generated: {timestamp} */
#ifndef FALL_SCALER_DATA_H
#define FALL_SCALER_DATA_H

#define FALL_SCALER_SEQ_LEN    {seq_len}
#define FALL_SCALER_N_FEATURES {n_features}

"""

TEMPLATE_FOOTER = """\
#endif /* FALL_SCALER_DATA_H */
"""


def format_array_2d(name, arr, seq_len, n_features):
    """Return a C definition for a static const float[seq_len][n_features] array."""
    lines = [f"/* Z-score {name.split('_')[-1]}, shape [{seq_len}][{n_features}] */"]
    lines.append(f"static const float {name}[{seq_len}][{n_features}] = {{")
    for t in range(seq_len):
        vals = ", ".join(f"{arr[t, f]:.8f}f" for f in range(n_features))
        comma = "," if t < seq_len - 1 else ""
        lines.append(f"  {{ {vals} }}{comma}")
    lines.append("};\n")
    return "\n".join(lines)


def main():
    repo_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--scaler", default=os.path.join(repo_root, "scaler.npz"),
                        help="Path to scaler.npz (default: <repo>/scaler.npz)")
    parser.add_argument("--out", default=os.path.join(repo_root, "Inc", "fall_scaler_data.h"),
                        help="Output header path (default: <repo>/Inc/fall_scaler_data.h)")
    args = parser.parse_args()

    # Load
    if not os.path.exists(args.scaler):
        sys.exit(f"ERROR: scaler file not found: {args.scaler}")

    data = np.load(args.scaler)
    if "mean" not in data or "std" not in data:
        sys.exit(f"ERROR: scaler.npz must contain 'mean' and 'std', got: {list(data.keys())}")

    mean = data["mean"].astype(np.float32)
    std  = data["std"].astype(np.float32)

    # Validate shape
    for arr_name, arr in [("mean", mean), ("std", std)]:
        if arr.ndim == 3 and arr.shape[0] == 1:
            arr = arr[0]  # strip batch dim → (30, 51)
        if arr.ndim != 2:
            sys.exit(f"ERROR: {arr_name} has unexpected shape {arr.shape}, expected (1,30,51) or (30,51)")
        if arr_name == "mean":
            mean = arr
        else:
            std = arr

    seq_len, n_features = mean.shape
    if std.shape != (seq_len, n_features):
        sys.exit(f"ERROR: mean shape {mean.shape} != std shape {std.shape}")

    if np.any(std < 1e-9):
        print("WARNING: std contains near-zero values – check scaler.npz", file=sys.stderr)

    # Generate
    os.makedirs(os.path.dirname(args.out), exist_ok=True)

    with open(args.out, "w") as f:
        f.write(TEMPLATE_HEADER.format(
            npz_name=os.path.basename(args.scaler),
            timestamp=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            seq_len=seq_len,
            n_features=n_features,
        ))
        f.write(format_array_2d("fall_scaler_mean", mean, seq_len, n_features))
        f.write("\n")
        f.write(format_array_2d("fall_scaler_std", std, seq_len, n_features))
        f.write(TEMPLATE_FOOTER)

    print(f"Written {args.out}  ({seq_len}x{n_features}, mean range [{mean.min():.4f}, {mean.max():.4f}],"
          f" std range [{std.min():.4f}, {std.max():.4f}])")


if __name__ == "__main__":
    main()
